on:
  push:
    paths-ignore:
      - "docs/**"
      - "README.MD"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.MD"

jobs:
  check-type-and-style:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Pre-Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy black isort

      - name: Install dependencies
        run: |
          python deps\install_deps.py
          python deps\install_mypy_types.py

      - name: Run type check
        run: |
          python -m tools check_type

      - name: Check code format
        run: |
          python -m tools format --check

      - name: Clean caches
        run: |
          python -m tools clean

  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Pre-Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python deps\install_deps.py

      - name: Run tests
        run: |
          python -m unittest discover -s tests --verbose

      - name: Clean caches
        run: |
          python -m tools clean
