on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  python-type-check:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pre-dependencies
        run: |
          pip install mypy black isort

      - name: Run type check
        run: |
          python -m script check_type

      - name: Check code format
        run: |
          python -m script format --check

      - name: Run tests
        run: |
          python -m unittest discover -s tests --verbose

      - name: Clean caches
        run: |
          python -m script clean
